import "./globals.css";
import Header from "../../component/Header";
export const metadata = {
  title: "Jerry Blog",
  description: "Generated by Jeong Hwan Lee",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Header />
        {children}
        {/* <>Main 페이지 입니다.</> */}
      </body>
    </html>
  );
}
